import { Injectable } from '@angular/core';
import { Card } from 'src/app/interfaces/card';
import { DateTransformService } from 'src/app/pipes/date-transform.service';

@Injectable({
  providedIn: 'root',
})
export class CardsService {
  constructor(private dateTransformService: DateTransformService) {}

  getCards(): Card[] {
    return [
      {
        id: 0,
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gatit.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        title: 'Robotii de azi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/roboti.png',
        startDateTime: new Date(2023, 8, 24, 9, 0),
        endDateTime: new Date(2023, 8, 24, 12, 0),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Complex Studentesc',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: true,
      },
      {
        id: 2,
        title: 'Teatru papusi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/teatru_papusi.png',
        startDateTime: new Date(2023, 9, 24, 7, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 9, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Centru',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 3,
        title: 'Expozitie artistica',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/expozitie-arta.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: true,
      },
      {
        id: 4,
        title: 'Expozitie Gradina Botanica',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gradina-botanica.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata 700',
        eventLink: '',
        ticketLink: '',
        createdBy: 'AdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 5,
        title: 'The Motans',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/The Motans.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 6,
        title: 'Concert Copii',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concert-copii.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 7,
        title: 'Concert Delia',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/Delia.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: true,
      },
      {
        id: 8,
        title: 'Concert Thalia',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concert Thalia.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 9,
        title: 'Calatorie in Cosmos',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: true,
      },
      {
        id: 10,
        title: 'Muzeul Satului',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/muzeul-satului.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 11,
        title: 'Concurs Pictura',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concurs-pictura.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 12,
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gatit.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: true,
      },
      {
        id: 13,
        title: 'Robotii de azi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/roboti.png',
        startDateTime: new Date(2023, 8, 24, 9, 0),
        endDateTime: new Date(2023, 8, 24, 12, 0),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Complex Studentesc',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 14,
        title: 'Teatru papusi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/teatru_papusi.png',
        startDateTime: new Date(2023, 9, 24, 7, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 9, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Centru',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 15,
        title: 'Expozitie artistica',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/expozitie-arta.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 16,
        title: 'Expozitie Gradina Botanica',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gradina-botanica.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata 700',
        eventLink: '',
        ticketLink: '',
        createdBy: 'AdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 17,
        title: 'The Motans',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/The Motans.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 18,
        title: 'Concert Copii',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concert-copii.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 19,
        title: 'Concert Delia',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/Delia.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: true,
      },
    ];
  }
  getMyCards(): Card[] {
    return [
      {
        id: 0,
        title: 'Concurs Pictura',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concurs-pictura.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gatit.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 2,
        title: 'Robotii de azi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/roboti.png',
        startDateTime: new Date(2023, 8, 24, 9, 0),
        endDateTime: new Date(2023, 8, 24, 12, 0),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Complex Studentesc',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 3,
        title: 'Teatru papusi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/teatru_papusi.png',
        startDateTime: new Date(2023, 9, 24, 7, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 9, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Centru',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 4,
        title: 'Expozitie artistica',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/expozitie-arta.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 5,
        title: 'Expozitie Gradina Botanica',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gradina-botanica.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata 700',
        eventLink: '',
        ticketLink: '',
        createdBy: 'AdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 6,
        title: 'The Motans',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/The Motans.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 7,
        title: 'Concert Copii',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concert-copii.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 8,
        title: 'Concert Delia',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/Delia.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 9,
        title: 'Concert Thalia',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concert Thalia.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 10,
        title: 'Calatorie in Cosmos',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 11,
        title: 'Muzeul Satului',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/muzeul-satului.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 12,
        title: 'Concurs Pictura',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concurs-pictura.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 13,
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gatit.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 14,
        title: 'Robotii de azi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/roboti.png',
        startDateTime: new Date(2023, 8, 24, 9, 0),
        endDateTime: new Date(2023, 8, 24, 12, 0),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Complex Studentesc',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 15,
        title: 'Concurs Pictura',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concurs-pictura.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 16,
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gatit.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 17,
        title: 'Robotii de azi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/roboti.png',
        startDateTime: new Date(2023, 8, 24, 9, 0),
        endDateTime: new Date(2023, 8, 24, 12, 0),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Complex Studentesc',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 18,
        title: 'Teatru papusi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/teatru_papusi.png',
        startDateTime: new Date(2023, 9, 24, 7, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 9, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Centru',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
    ];
  }
  getMostPopularCards(): Card[] {
    return [
      {
        id: 0,
        title: 'Concert Thalia',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concert Thalia.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        title: 'Expozitie Gradina Botanica',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/gradina-botanica.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata 700',
        eventLink: '',
        ticketLink: '',
        createdBy: 'AdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 2,
        title: 'Muzeul Satului',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/muzeul-satului.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 3,
        title: 'Concurs Pictura',
        location: 'Union Square',
        author: 'AdminName',
        imageURL: './assets/img/concurs-pictura.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
    ];
  }
  transformCardsDateFormat(cards: Card[]): any[] {
    return cards.map((card) => {
      return {
        ...card,
        startDateTime: this.dateTransformService.transformStartDate(
          card.startDateTime
        ),
        startTime: this.dateTransformService.transformStartTime(card.startTime),
      };
    });
  }
}
