import { Injectable } from '@angular/core';
import { Card } from 'src/app/interfaces/card';

@Injectable({
  providedIn: 'root',
})
export class CardsService {
  constructor() {}

  getCards(): Card[] {
    return [
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Robotii de azi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img4.png',
        startDateTime: new Date(2023, 8, 24, 9, 0),
        endDateTime: new Date(2023, 8, 24, 12, 0),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Complex Studentesc',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Teatru papusi',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img10.png',
        startDateTime: new Date(2023, 9, 24, 7, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 9, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img1.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img3.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: false,
        isFavorite: false,
      },
    ];
  }
  getMyCards(): Card[] {
    return [
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img4.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img4.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 10, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 8, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
    ];
  }
  getMostPopularCards(): Card[] {
    return [
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/universe.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img4.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: false,
        isDraft: false,
        isFavorite: false,
      },
      {
        id: 1,
        date: '12 JUNE 2023',
        time: '20:00',
        title: 'Cursuri Gatit',
        location: 'Union Square',
        author: 'OtherAdminName',
        imageURL: './assets/img/img5.png',
        startDateTime: new Date(2023, 1, 24, 9, 43),
        endDateTime: new Date(2023, 1, 24, 9, 43),
        startTime: new Date(2023, 1, 24, 9, 43),
        duration: new Date(2023, 1, 24, 9, 43),
        address: 'Piata Victoriei',
        eventLink: '',
        ticketLink: '',
        createdBy: 'OtherAdminName',
        isPetFriendly: false,
        isKidFriendly: false,
        isFree: true,
        isDraft: true,
        isFavorite: false,
      },
    ];
  }
}
